http:
  routers:
    adguard-home:
      entryPoints:
        - websecure
      rule: Host(`adguard.<MY-DOMAIN>.com`)
      middlewares:
        - secured-auth@file
      service: adguard-home

  services:
    adguard-home:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://192.168.0.101
